apiVersion: v1
kind: Service
metadata:
  name: astronomy-service
  namespace: starroll
spec:
  selector:
    app: astronomy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
