apiVersion: batch/v1
kind: CronJob
metadata:
  name: gmp-datasource-syncer
  namespace: starroll
spec:
  schedule: "*/10 * * * *" # 每 10 分钟运行一次
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: grafana-sa
          containers:
            - name: syncer
              image: gke.gcr.io/prometheus-engine/datasource-syncer:v0.18.0-gke.2
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "100m"
                  memory: "256Mi"
              args:
                - "--project-id=starroll"
                - "--grafana-api-endpoint=http://grafana-service:3000"
                - "--grafana-api-token=$(GRAFANA_API_KEY)"
                - "--datasource-uids=ffior0pj9wa2of"
              env:
                - name: GRAFANA_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-api-credentials
                      key: token
          restartPolicy: Never
