apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: starroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana-sa
      securityContext:
        runAsUser: 0
      containers:
        - name: main
          image: grafana/grafana:12.3
          imagePullPolicy: Always
          env:
            - name: GF_SERVER_ROOT_URL
              value: https://starroll.ie/grafana/
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
