apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: console
  namespace: starroll
spec:
  serviceName: console-headless-service
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: main
          image: europe-west1-docker.pkg.dev/starroll/console/console:0.1
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app-env-file
              mountPath: /app/.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: "2000m"
              memory: "4096Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: app-env-file
          secret:
            secretName: starroll-secret
            items:
              - key: .env
                path: .env
