import asyncio
import json
import pytest
from datetime import datetime
from unittest.mock import MagicMock
from fastapi import HTTPException
from sqlalchemy.orm import Session

# Import the module under test and its dependencies
from backend.console.handler import get_identify_stars_job_result as handler_module
from backend.console.handler.get_identify_stars_job_result import api_get_identify_stars_job_result_post
from backend.console.dal.rds.identify_stars_job import IdentifyStarsJob as IdentifyStarsJobDAL
from gen.py.src.openapi_server.models.api_get_identify_stars_job_result_post_request import ApiGetIdentifyStarsJobResultPostRequest

class TestApiGetIdentifyStarsJobResultPost:
    """Test cases for api_get_identify_stars_job_result_post handler."""

    def _create_valid_request(self, user_id="123", job_id="3", token="valid_token"):
        """Helper to create a valid request."""
        return ApiGetIdentifyStarsJobResultPostRequest(
            user_credentials={"user_id": user_id, "token": token},
            job_id=job_id
        )

    def test_api_get_identify_stars_job_result_success(
        self, db_session: Session, monkeypatch: pytest.MonkeyPatch
    ):
        """Test successful retrieval and parsing of star identification results."""
        user_id = 123
        job_id = 3
        
        # Mock result data (stringified JSON as found in your DB)
        mock_result_blob = json.dumps({
            "calibration": {"ra": 206.31, "dec": 3.33, "radius": 1.2, "orientation": 290.4},
            "stars": [{"names": ["Spica"], "pixelx": 349.9, "pixely": 721.7, "vmag": 0.9}]
        })

        # Mock Database Object
        mock_job = MagicMock()
        mock_job.id = job_id
        mock_job.user_id = user_id
        mock_job.status = "COMPLETED"
        mock_job.result = mock_result_blob
        mock_job.image_key = "test/image.jpg"
        mock_job.created_at = datetime.now()

        # Set up Mocks
        def _get_db_override():
            yield db_session

        def _verify_auth_override(token, uid):
            pass

        monkeypatch.setattr(handler_module, "get_db", _get_db_override)
        monkeypatch.setattr(handler_module, "verify_user_id_and_token", _verify_auth_override)
        monkeypatch.setattr(IdentifyStarsJobDAL, "get_by_id", lambda db, jid: mock_job)

        # Execute
        request = self._create_valid_request(user_id=str(user_id), job_id=str(job_id))
        result = asyncio.run(api_get_identify_stars_job_result_post(request))

        
        # Verify
        assert len(result.identify_stars_jobs_list) == 1
        job_data = result.identify_stars_jobs_list[0]

        # 1. Check Center (Note the snake_case generated by Pydantic)
        assert job_data.center.right_ascension == 206.31
        assert job_data.center.declination == 3.33

        # 2. Check Stars
        assert len(job_data.identified_stars) == 1
        star = job_data.identified_stars[0]
        assert star.names[0] == "Spica"
        assert star.pixel_x == 349.9
        assert star.pixel_y == 721.7

    def test_api_get_identify_stars_job_result_not_found(
        self, db_session: Session, monkeypatch: pytest.MonkeyPatch
    ):
        """Test error when job ID does not exist."""
        def _get_db_override(): yield db_session
        def _verify_auth_override(token, uid): pass

        monkeypatch.setattr(handler_module, "get_db", _get_db_override)
        monkeypatch.setattr(handler_module, "verify_user_id_and_token", _verify_auth_override)
        monkeypatch.setattr(IdentifyStarsJobDAL, "get_by_id", lambda db, jid: None)

        request = self._create_valid_request(job_id="999")

        with pytest.raises(HTTPException) as exc_info:
            asyncio.run(api_get_identify_stars_job_result_post(request))

        assert exc_info.value.status_code == 404
        assert exc_info.value.detail == "Job not found"

    def test_api_get_identify_stars_job_result_unauthorized(
        self, db_session: Session, monkeypatch: pytest.MonkeyPatch
    ):
        """Test error when user tries to access a job belonging to someone else."""
        mock_job = MagicMock()
        mock_job.user_id = 999  # Owner is different from requester

        def _get_db_override(): yield db_session
        def _verify_auth_override(token, uid): pass

        monkeypatch.setattr(handler_module, "get_db", _get_db_override)
        monkeypatch.setattr(handler_module, "verify_user_id_and_token", _verify_auth_override)
        monkeypatch.setattr(IdentifyStarsJobDAL, "get_by_id", lambda db, jid: mock_job)

        request = self._create_valid_request(user_id="123") # Requester is 123

        with pytest.raises(HTTPException) as exc_info:
            asyncio.run(api_get_identify_stars_job_result_post(request))

        assert exc_info.value.status_code == 403
        assert exc_info.value.detail == "Unauthorized"