STAR_IDENTIFY_JOB_STATUS_PENDING = "Pending"
STAR_IDENTIFY_JOB_STATUS_STARTING = "Starting"
STAR_IDENTIFY_JOB_STATUS_RUNNING = "Running"
STAR_IDENTIFY_JOB_STATUS_FAILED = "Failed"
STAR_IDENTIFY_JOB_STATUS_SUCCEEDED = "Succeeded"

ASTRONOMY_NET_JOB_STATUS_SOLVING = "solving"
ASTRONOMY_NET_JOB_STATUS_SUCCESS = "success"
ASTRONOMY_NET_JOB_STATUS_FAILURE = "failure"
